-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM
(
SELECT s.BOOK_ID, b.PRICE, b.CATEGORY, b.AUTHOR_ID, a.AUTHOR_NAME, SUM(SALES) AS SALES
FROM BOOK_SALES s
JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID

WHERE SALES_DATE LIKE "2022-01%"
GROUP BY s.BOOK_ID
) AS a

GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC