SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM 
(
SELECT AUTHOR_ID, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES s JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY CATEGORY, AUTHOR_ID
) AS A
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC
