SELECT r.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW r 
JOIN REST_INFO i ON r.REST_ID = i.REST_ID
GROUP BY r.REST_ID 
HAVING ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC