-- 코드를 입력하세요
SELECT p.PRODUCT_ID, PRODUCT_NAME, SUM(o.AMOUNT * p.PRICE) AS TOTAL_SALES
From FOOD_ORDER o 
JOIN FOOD_PRODUCT p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID;
