-- 코드를 입력하세요
SELECT FLAVOR
FROM
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM 
    (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS COMBINED
    GROUP BY FLAVOR
    ORDER BY TOTAL DESC
) AS RESULT

LIMIT 3;



;