WITH RECURSIVE cte AS (
    SELECT 0 AS hour
    UNION ALL 
    SELECT hour + 1 
    FROM cte
    WHERE hour < 23
)

SELECT hour, COUNT(ANIMAL_ID) AS COUNT
FROM cte c LEFT JOIN ANIMAL_OUTS o ON c.hour = HOUR(o.DATETIME)
GROUP BY hour


