# SELECT ANIMAL_ID, NAME, CONCAT(YEAR(DATETIME), "-", MONTH(DATETIME), "-", DAY(DATETIME)) AS "날짜"
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID


SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID